[package]
default-run = "shooter_bevy"
name = "shooter_bevy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
opt-level = 3

[dependencies]
bevy = { version = "0.13.2", features = ["dynamic_linking"] }

[[bin]]
name = "shooter_test"
path = "src/bin/shooter_test/shooter_test.rs"
test = false
bench = false

[[bin]]
name = "bin2"
path = "src/bin2.rs"
test = false
bench = false

[[bin]]
name = "platformer"
path = "src/bin/platformer/platformer.rs"
test = false
bench = false

[[bin]]
name = "model3d"
path = "src/bin/model/model3d.rs"
test = false
bench = false

[[example]]
name = "hello_world"
path = "example/test.rs"
doc-scrape-examples = true

[[example]]
name = "example_00_text"
path = "example/example_00_text/text_rendering.rs"
doc-scrape-examples = true

[[example]]
name = "example_01_text_update"
path = "example/example_01_text_update/text_update.rs"
doc-scrape-examples = true